# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from credit_card.grpc import credit_card_pb2 as credit__card_dot_grpc_dot_credit__card__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class CreditCardControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/Create',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.SerializeToString,
                response_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
                )
        self.Destroy = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/Destroy',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardDestroyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.List = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/List',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListRequest.SerializeToString,
                response_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListResponse.FromString,
                )
        self.PartialUpdate = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/PartialUpdate',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardPartialUpdateRequest.SerializeToString,
                response_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
                )
        self.Retrieve = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/Retrieve',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRetrieveRequest.SerializeToString,
                response_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/hotel_rooms_users_services.credit_card.CreditCardController/Update',
                request_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.SerializeToString,
                response_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
                )


class CreditCardControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PartialUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retrieve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreditCardControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.FromString,
                    response_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardDestroyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListRequest.FromString,
                    response_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListResponse.SerializeToString,
            ),
            'PartialUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.PartialUpdate,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardPartialUpdateRequest.FromString,
                    response_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.SerializeToString,
            ),
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRetrieveRequest.FromString,
                    response_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.FromString,
                    response_serializer=credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hotel_rooms_users_services.credit_card.CreditCardController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreditCardController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/Create',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.SerializeToString,
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/Destroy',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardDestroyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/List',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListRequest.SerializeToString,
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PartialUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/PartialUpdate',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardPartialUpdateRequest.SerializeToString,
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/Retrieve',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRetrieveRequest.SerializeToString,
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/hotel_rooms_users_services.credit_card.CreditCardController/Update',
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardRequest.SerializeToString,
            credit__card_dot_grpc_dot_credit__card__pb2.CreditCardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
