# Generated by Django 5.0.4 on 2024-04-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0002_remove_creditcard_user_id_alter_creditcard_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'CreditCard', 'verbose_name_plural': 'CreditCards'},
        ),
    ]
